"""MIRA Prescription Database — 42 evidence-based therapeutic activities."""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Optional

@dataclass
class ActivityPrescription:
    name: str
    description: str
    steps: list[str]
    duration_minutes: int
    target_emotions: list[str]
    theory_basis: str
    evidence_level: str
    contraindications: list[str]
    difficulty: int  # 1-3
    companion_script: str

# fmt: off
PRESCRIPTIONS: list[ActivityPrescription] = [
    # ── ANXIETY (8) ──
    ActivityPrescription("Box Breathing","Structured breathing to activate parasympathetic response.",["Inhale 4 counts","Hold 4 counts","Exhale 4 counts","Hold 4 counts","Repeat 5 cycles"],5,["Anxiety","Panic","Fear"],"CBT","strong",[],1,"Let's breathe together. In… 2… 3… 4… hold… 2… 3… 4… out… 2… 3… 4…"),
    ActivityPrescription("5-4-3-2-1 Grounding","Sensory grounding to interrupt anxious spirals.",["Name 5 things you SEE","4 things you TOUCH","3 things you HEAR","2 things you SMELL","1 thing you TASTE"],5,["Anxiety","Dissociation","Panic"],"CBT","strong",[],1,"Look around. Tell me 5 things you can see right now."),
    ActivityPrescription("Progressive Muscle Relaxation","Systematic tension-release cycle through muscle groups.",["Tense feet 5 seconds, release","Tense calves, release","Continue up: thighs, abdomen, hands, arms, shoulders, face","Notice the difference between tension and relaxation"],15,["Anxiety","Tension","Insomnia"],"CBT","strong",["acute physical injury"],2,"Start with your feet. Curl your toes tight… hold… and release. Feel the warmth."),
    ActivityPrescription("Worry Time Scheduling","Contain worry to a scheduled 15-min window.",["Choose a daily 15-min worry slot","When worry arises outside slot, write it down and postpone","During worry time, review list and problem-solve","After 15 min, stop and move to a pleasant activity"],15,["Anxiety","Rumination"],"CBT","moderate",[],2,"Let's schedule your worry. Pick a time — say, 4pm. Until then, jot worries on a list and we'll deal with them together at 4."),
    ActivityPrescription("Cognitive Restructuring for Predictions","Challenge anxious predictions with evidence.",["Write the anxious prediction","Rate belief 0-100%","List evidence FOR","List evidence AGAINST","Write balanced prediction","Re-rate belief"],15,["Anxiety","Fortune-telling"],"CBT","strong",[],2,"What's your mind predicting? Let's write it down and examine the evidence like a detective."),
    ActivityPrescription("Interoceptive Exposure","Sit with physical anxiety sensations safely.",["Identify the physical sensation (racing heart, tight chest)","Rate intensity 0-10","Stay with it without escaping for 2 minutes","Notice: does intensity change on its own?","Reflect: the sensation is uncomfortable but not dangerous"],10,["Anxiety","Panic","Somatic"],"CBT","strong",["cardiac conditions","PTSD without therapist"],3,"Your body is sending alarm signals, but you are safe. Let's sit with the feeling and watch what happens."),
    ActivityPrescription("Safety Behavior Reduction","Gradually drop avoidance behaviors.",["Identify one safety behavior you use (checking, reassurance-seeking)","Reduce it by 50% today","Notice: did the feared outcome happen?","Journal your observation"],20,["Anxiety","OCD patterns"],"CBT","moderate",["active crisis"],2,"What's one thing you do to feel safe that might be keeping anxiety alive? Let's experiment with doing less of it."),
    ActivityPrescription("Mindful Observation of Anxiety","Non-judgmental attention to anxious experience.",["Sit comfortably. Close eyes.","Scan body for anxiety sensations","Label each: 'tightness in chest', 'butterflies in stomach'","Observe without changing anything for 3 minutes","Open eyes. Notice any shift."],8,["Anxiety","Tension"],"ACT","moderate",[],1,"Let's just observe the anxiety like a curious scientist. No fixing, just noticing."),
    # ── DEPRESSION (8) ──
    ActivityPrescription("Behavioral Activation","Schedule one pleasant activity regardless of motivation.",["Choose one small pleasant activity (walk, music, tea)","Do it within the next hour","Rate mood before (0-10) and after (0-10)","Notice: action came before motivation, not after"],20,["Sadness","Depression","Anhedonia"],"Behaviourism","strong",[],1,"You don't need to feel like doing it first. Pick one tiny thing — even making tea counts. Mood follows action."),
    ActivityPrescription("Anti-Rumination Technique","Break repetitive negative thought loops.",["Notice you're ruminating","Say 'I'm ruminating' (label it)","Engage one sense fully: describe something you see in detail","Shift to an absorbing activity for 10 minutes"],10,["Sadness","Rumination","Depression"],"CBT","moderate",[],1,"Your mind is stuck in a loop. Let's interrupt it. Describe this room to me in vivid detail — colors, textures, shapes."),
    ActivityPrescription("Opposite Action","Do the opposite of what depression urges.",["Depression says: stay in bed → get up","Depression says: isolate → contact someone","Depression says: skip hygiene → take a shower","Choose ONE opposite action now"],15,["Sadness","Depression","Withdrawal"],"DBT","strong",[],2,"Depression is telling you to withdraw. What would the opposite look like? Even a small opposite action counts."),
    ActivityPrescription("Gratitude Practice","Specific gratitude with reasons.",["Write 3 specific things you're grateful for today","For each, write WHY (the reason matters more than the thing)","Read them aloud to yourself"],10,["Sadness","Negativity bias"],"Positive Psychology","moderate",["acute grief — use with sensitivity"],1,"Not 'I'm grateful for family' — more like 'I'm grateful my sister called yesterday because it reminded me someone thinks of me.'"),
    ActivityPrescription("Exercise Prescription","20-minute walk for mood elevation.",["Put on shoes (the hardest step)","Walk outside for 10 minutes in any direction","Turn around and walk back","Notice your mood shift after"],20,["Sadness","Depression","Lethargy"],"Behaviourism","strong",["physical disability — adapt"],1,"Step one is shoes. That's it. Just shoes. Then the door. One step at a time."),
    ActivityPrescription("Social Connection Experiment","One micro-interaction to combat isolation.",["Choose one person (friend, family, colleague)","Send a short message: 'Hey, was thinking of you'","No expectations for response","Journal how sending it felt"],10,["Sadness","Loneliness","Isolation"],"Attachment","moderate",[],1,"Send one message to someone. Not a deep conversation — just 'thinking of you.' Connection starts small."),
    ActivityPrescription("Self-Compassion Break","Kristin Neff's 3-step self-compassion.",["Say: 'This is a moment of suffering' (mindfulness)","Say: 'Suffering is part of being human' (common humanity)","Place hand on heart. Say: 'May I be kind to myself' (self-kindness)"],5,["Sadness","Shame","Self-criticism"],"Compassion-Focused","strong",[],1,"Put your hand on your heart. Say: 'This hurts, and that's okay. I deserve kindness right now.'"),
    ActivityPrescription("Activity Scheduling","Structured daily plan with mastery + pleasure.",["Plan tomorrow: morning, afternoon, evening","Include 1 mastery activity (cooking, cleaning, work task)","Include 1 pleasure activity (music, nature, hobby)","Include 1 connection activity (text, call, visit)","Rate each 0-10 after completing"],30,["Depression","Anhedonia","Structure"],"CBT","strong",[],2,"Let's plan tomorrow together. Not a perfect day — just a day with one thing you can be proud of and one thing you enjoy."),
    # ── ANGER (6) ──
    ActivityPrescription("STOP Technique","Interrupt anger escalation in the moment.",["S — Stop. Freeze. Don't react.","T — Take a breath. One deep slow breath.","O — Observe. What am I feeling? What triggered this?","P — Proceed mindfully. Choose your response."],3,["Anger","Frustration","Irritability"],"CBT","strong",[],1,"STOP. Before you do anything, take one breath. Just one. Good. Now, what just happened?"),
    ActivityPrescription("20-Minute Time-Out","Strategic withdrawal to cool down.",["Tell the other person: 'I need 20 minutes'","Leave the situation physically","Do something physical: walk, stretch, cold water on wrists","Return after 20 min with calmer perspective"],20,["Anger","Rage","Conflict"],"CBT","strong",[],1,"Step away for 20 minutes. Not running away — cooling down. Splash cold water on your wrists. We'll process when you're ready."),
    ActivityPrescription("Cognitive Reappraisal","Reinterpret the triggering situation.",["Describe the trigger objectively (facts only)","What meaning did you assign? ('They disrespected me')","What are 3 alternative interpretations?","Which interpretation has the most evidence?"],15,["Anger","Frustration"],"CBT","strong",[],2,"Let's separate what happened from what your mind added to it. What are the bare facts?"),
    ActivityPrescription("Assertiveness Training","Express needs without aggression.",["Use the formula: 'I feel X when Y happens, and I need Z'","Practice with a recent situation","Focus on YOUR feelings and needs, not their behavior","Role-play the conversation"],15,["Anger","Frustration","Resentment"],"CBT","moderate",[],2,"Try: 'I feel frustrated when plans change last minute because I value my time. I need advance notice.'"),
    ActivityPrescription("Physical Release","Channel anger energy into movement.",["Choose: fast walk, push-ups, or cleaning vigorously","Go at high intensity for 10 minutes","Gradually slow down over 5 minutes","Notice the energy shift in your body"],15,["Anger","Rage","Tension"],"Behaviourism","moderate",[],1,"Your body has anger energy that needs to go somewhere. Let's channel it — what can you do right now? Walk fast? Push-ups?"),
    ActivityPrescription("Empathy Activation","Perspective-taking to soften anger.",["Imagine the person who angered you as a child","What might they be struggling with right now?","Write one sentence of understanding (not excusing)","Notice any shift in your anger intensity"],10,["Anger","Resentment"],"Rogers","moderate",["abuser — do NOT empathize with abuser"],2,"This isn't about excusing them. What might be going on in their life that contributed to their behavior?"),
    # ── SHAME/GUILT (5) ──
    ActivityPrescription("Self-Compassion Break (Neff)","3-step compassion for shame.",["Mindfulness: 'This is painful. I feel shame.'","Common humanity: 'Everyone feels this way sometimes.'","Self-kindness: 'What would I say to a friend feeling this?'"],5,["Shame","Guilt","Self-loathing"],"Compassion-Focused","strong",[],1,"Shame makes you feel alone. But right now, thousands of people feel exactly what you feel. You're human."),
    ActivityPrescription("Responsibility Pie Chart","Distribute responsibility fairly.",["Draw a circle (pie chart)","List ALL factors that contributed to the situation","Assign percentage to each factor","Your slice is usually smaller than shame tells you"],15,["Guilt","Personalization","Self-blame"],"CBT","moderate",[],2,"Let's make a pie chart of everyone and everything that contributed. Where does your actual responsibility end?"),
    ActivityPrescription("Shame Resilience","Brené Brown's shame resilience steps.",["Recognize shame: physical signs (hot face, small feeling)","Reach out: tell ONE safe person","Speak shame: name it specifically, it loses power","Reality check: separate what I did from who I am"],15,["Shame","Vulnerability"],"Brené Brown","moderate",[],2,"Shame grows in silence and secrecy. Naming it takes its power away. What specifically are you feeling shame about?"),
    ActivityPrescription("Amends vs Guilt Differentiation","Separate productive guilt from toxic shame.",["Did I violate MY values? (guilt) Or someone else's expectations? (shame)","If guilt: what specific action can I take to repair?","If shame: whose voice am I hearing? Is it mine?","Make amends if needed, then actively release"],15,["Guilt","Shame"],"CBT","moderate",[],2,"Guilt says 'I did something bad.' Shame says 'I AM bad.' Which one is speaking right now?"),
    ActivityPrescription("Common Humanity Meditation","You are not alone in suffering.",["Sit quietly. Breathe.","Think of your pain. Say: 'This is suffering.'","Now imagine 1000 people feeling exactly this right now.","Say: 'I am not alone. This is part of being human.'","Send yourself compassion: 'May I find peace.'"],10,["Shame","Isolation","Self-criticism"],"Compassion-Focused","moderate",[],1,"Close your eyes. Right now, across the world, thousands of people feel exactly what you feel. You are not broken. You are human."),
    # ── LONELINESS (4) ──
    ActivityPrescription("Micro-Connection Experiment","One tiny social interaction.",["Choose: smile at someone, compliment a stranger, text an old friend","Do it today — no expectations for outcome","Notice how the ACT of connecting feels","Journal: 'I reached out, and I survived.'"],10,["Loneliness","Isolation"],"Behaviourism","moderate",[],1,"Connection doesn't have to be deep. A smile, a 'thank you', a text — these count. What's one micro-connection you can make today?"),
    ActivityPrescription("Self-Companionship Practice","Be your own kind companion.",["Write a letter to yourself from a loving friend","What would they notice about you? What would they say?","Read it aloud. Receive the words."],15,["Loneliness","Self-worth"],"Rogers","moderate",[],1,"You are your own longest relationship. Write yourself a letter — what would your kindest friend say to you right now?"),
    ActivityPrescription("Interest-Based Social Activity","Find belonging through shared interests.",["List 3 interests/hobbies you enjoy","Search for one local or online group (Reddit, Discord, meetup)","Observe/lurk for a week, then make one comment or attend once","No pressure to become best friends — just be present"],30,["Loneliness","Belonging"],"Maslow","moderate",["social anxiety — start online only"],2,"Connection is easier when you share something in common. What do you enjoy? Let's find others who enjoy it too."),
    ActivityPrescription("Digital Connection Intentionally","Use technology for meaningful connection.",["Choose ONE person you haven't talked to in a while","Send a voice note (more personal than text)","Share something specific: a memory, a question, a photo","Be okay if they don't respond immediately"],10,["Loneliness","Disconnection"],"Attachment","moderate",[],1,"A voice note to someone you miss. Not 'hey' — something real. 'I was thinking about that time we…'"),
    # ── FEAR/DREAD (4) ──
    ActivityPrescription("Gradual Exposure Hierarchy","Face fears step by step.",["List feared situations 1-10 (1=mild, 10=worst)","Start with level 1-2 this week","Stay in the situation until anxiety drops by half","Move to next level only when current level feels manageable"],30,["Fear","Phobia","Avoidance"],"CBT","strong",["trauma — only with therapist guidance"],3,"We start small. What's a fear level 1 for you? Something slightly uncomfortable but manageable."),
    ActivityPrescription("Window of Tolerance Education","Understand your stress capacity.",["Learn: hyper-arousal (panic, rage) vs hypo-arousal (numb, frozen)","Your window = the zone where you can think AND feel","When outside window: grounding brings you back","Track: what pushes you out? What brings you back in?"],15,["Fear","Overwhelm","Dysregulation"],"Polyvagal","moderate",[],2,"Everyone has a window — a zone where emotions are manageable. Let's find yours and learn what keeps you in it."),
    ActivityPrescription("Present-Moment Grounding","Anchor to the here and now.",["Feel your feet on the ground. Press down.","Name where you are. What day is it? What time?","Touch something with texture. Describe it.","Say: 'Right now, in this moment, I am safe.'"],5,["Fear","Dread","Anticipatory anxiety"],"ACT","strong",[],1,"Fear lives in the future. Let's come back to now. Feel your feet. You are here. You are safe."),
    ActivityPrescription("Brave Action Experiment","One small act of courage.",["Choose ONE thing fear is stopping you from doing","Scale it down to the smallest possible version","Do it today with self-compassion if it's hard","Journal: 'I was brave when I…'"],20,["Fear","Avoidance"],"ACT","moderate",[],2,"Bravery isn't the absence of fear — it's action despite fear. What's one tiny brave thing you can do today?"),
    # ── NUMBING/DISSOCIATION (4) ──
    ActivityPrescription("Sensory Grounding","Strong sensory input to reconnect.",["Hold an ice cube in your hand (30 seconds)","Smell something strong (coffee, peppermint, lemon)","Splash cold water on your face","Stamp your feet firmly on the ground 10 times"],5,["Numbness","Dissociation","Blunting"],"CBT","strong",[],1,"Let's wake up your senses. Hold something cold — ice, a cold glass. Feel the shock. You're here."),
    ActivityPrescription("Body Scan Reconnection","Systematic reconnection with physical self.",["Lie down or sit. Close eyes.","Start at toes: 'What do I feel here?'","Move up slowly: feet, legs, hips, belly, chest, arms, face","Wherever you feel nothing, just notice that too","Spend extra time where you DO feel something"],15,["Numbness","Disconnection","Alexithymia"],"Mindfulness","moderate",[],1,"Let's find you in your body. Start at your toes. Anything there? Warmth? Tingling? Nothing? All answers are okay."),
    ActivityPrescription("Titrated Feeling Exposure","Safely access emotions in small doses.",["Think of something mildly emotional (not the hardest thing)","Stay with the feeling for 30 seconds only","Then shift to your safe place or grounding","Repeat, gradually extending time with feeling"],15,["Numbness","Emotional avoidance"],"Somatic","moderate",["severe trauma without therapist"],2,"We're going to feel — just a tiny bit. Like dipping a toe in water. You control how much and when to come back to shore."),
    ActivityPrescription("Pendulation","Oscillate between resource and distress.",["Find your resource: a memory, place, or sensation that feels safe","Feel it fully for 1 minute","Briefly touch the difficult feeling (10 seconds)","Return to resource immediately","Repeat, building tolerance"],15,["Dissociation","Overwhelm","Trauma response"],"Somatic Experiencing","moderate",["severe dissociation without professional support"],3,"Pendulation: swing between safety and discomfort. Like stretching a muscle — a little at a time. Always returning to safety."),
    # ── CRISIS IMMEDIATE (3) ──
    ActivityPrescription("Safety Plan (Stanley-Brown)","Evidence-based crisis safety planning.",["Step 1: Warning signs (what do I notice first?)","Step 2: Internal coping (what can I do alone?)","Step 3: Social contacts who can distract","Step 4: People I can ask for help","Step 5: Professionals/crisis lines to contact","Step 6: Making the environment safe"],30,["Crisis","Suicidal ideation"],"Stanley-Brown","strong",[],3,"Let's build your safety plan together. This isn't for right now — it's your anchor for hard moments. Step 1: what are your early warning signs?"),
    ActivityPrescription("Reasons for Living List","Anchor to what matters.",["Write 5 reasons to keep going — however small","Include: people, pets, experiences, future hopes, values","Read the list aloud","Keep it in your phone, wallet, or mirror"],15,["Crisis","Hopelessness","Despair"],"CBT","moderate",[],1,"Even one reason counts. A pet waiting at home. A song you haven't heard yet. A person who would miss your laugh. What comes to mind?"),
    ActivityPrescription("Crisis Warm Handoff","Compassionate resource connection.",["Acknowledge the pain: 'This is real and valid.'","Normalize help-seeking: 'Reaching out is strength.'","Provide resource naturally: 'Umang Helpline is available — 0311-7786264, 24/7, free, confidential.'","Offer to stay present while they consider calling"],5,["Crisis","Active distress"],"Crisis Intervention","strong",[],1,"You don't have to do this alone. There are people trained for exactly this moment. Would it feel okay to talk about reaching out?"),
]
# fmt: on


class PrescriptionSelector:
    """Rank and filter prescriptions for a user."""

    def rank_prescriptions(
        self,
        emotion: str,
        recent_prescriptions: list[str] | None = None,
        difficulty_pref: int = 2,
        k: int = 5,
    ) -> list[ActivityPrescription]:
        recent = set(recent_prescriptions or [])
        candidates: list[tuple[float, ActivityPrescription]] = []

        for rx in PRESCRIPTIONS:
            if rx.name in recent:
                continue
            emotion_match = 1.0 if emotion in rx.target_emotions else 0.0
            # Partial match on category
            if emotion_match == 0.0:
                emotion_lower = emotion.lower()
                if any(emotion_lower in t.lower() for t in rx.target_emotions):
                    emotion_match = 0.5
            evidence_weight = {"strong": 1.0, "moderate": 0.7, "weak": 0.3}.get(rx.evidence_level, 0.5)
            difficulty_fit = 1.0 - abs(rx.difficulty - difficulty_pref) * 0.3
            score = emotion_match * 0.5 + evidence_weight * 0.3 + difficulty_fit * 0.2
            if emotion_match > 0:
                candidates.append((score, rx))

        candidates.sort(key=lambda x: x[0], reverse=True)
        return [rx for _, rx in candidates[:k]]
